"""Remove username field and make encrypted_username required

Revision ID: d37add2f6fec
Revises: 6c44f5232e47
Create Date: 2025-05-12 15:01:46.540038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37add2f6fec'
down_revision = '6c44f5232e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('encrypted_username',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint('uq_user_encrypted_username', ['encrypted_username'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_constraint('uq_user_encrypted_username', type_='unique')
        batch_op.alter_column('encrypted_username',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
